### ISSUE TITLE
Crash when initializing plugin

### ISSUE THREAD

**Issue by mildred** [firecow/caddy-forward-auth#13]
With the latest Caddy using this plugin as downloaded from https://caddyserver.com/download?package=github.com%2Ffirecow%2Fcaddy-forward-auth the Caddy server crashes with:

```
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.RegisterDirective(...)
	github.com/caddyserver/caddy/v2@v2.5.1/caddyconfig/httpcaddyfile/directives.go:100
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.RegisterHandlerDirective({0x199a9ee?, 0xc?}, 0x1a84658?)
	github.com/caddyserver/caddy/v2@v2.5.1/caddyconfig/httpcaddyfile/directives.go:110 +0x114
github.com/firecow/caddy-forward-auth.init.0()
	github.com/firecow/caddy-forward-auth@v0.0.0-20220506175350-80b7a56c2cfa/forwardauth.go:16 +0x5e
```

**Comment by mildred** [comment]
Oops, that might be because this is now a standard Caddy feature...

**Comment by firecow** [comment]
It's not implemented in Caddy.. 
Caddy just overtook the forward_auth directive.
I'll be renaming this to something or discontinuing it if the native Caddy can do my bidding 😁

**Comment by firecow** [comment]
https://github.com/firecow/caddy-forward-auth/blob/main/README.md
Native Caddy can !!!!
